# Generated by Django 2.1.1 on 2018-09-05 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElementType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=50)),
                ('description', models.TextField(max_length=300)),
                ('height', models.TextField(max_length=7)),
                ('weight', models.DecimalField(decimal_places=1, max_digits=4)),
                ('category', models.TextField(max_length=20)),
                ('overgrow', models.TextField(max_length=20)),
                ('hp', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('specattack', models.IntegerField()),
                ('specdefense', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('type1', models.TextField(max_length=20)),
                ('type2', models.TextField(max_length=20)),
                ('weakness1', models.TextField(max_length=20)),
                ('weakness2', models.TextField(max_length=20)),
                ('weakness3', models.TextField(max_length=20)),
                ('weakness4', models.TextField(max_length=20)),
                ('weakness5', models.TextField(max_length=20)),
                ('weakness6', models.TextField(max_length=20)),
            ],
        ),
    ]
