# Generated by Django 2.1.1 on 2018-09-05 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_delete_elementtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='weakness7',
            field=models.TextField(default='exit', max_length=20),
            preserve_default=False,
        ),
    ]
