# Generated by Django 2.1.1 on 2018-09-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0005_auto_20180905_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='description',
            field=models.CharField(help_text='Description', max_length=300),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='id',
            field=models.IntegerField(help_text='Pokemon ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='name',
            field=models.CharField(help_text='Pokemon', max_length=50),
        ),
    ]
